class KoreanFood {
  final int id;
  final String name;
  final String englishName;

  KoreanFood({required this.id, required this.name, required this.englishName});

  static List<KoreanFood> foods = [
    KoreanFood(id: 1, name: '치킨', englishName: 'Chicken'),
    KoreanFood(id: 2, name: '생선구이', englishName: 'baked fish'),
    KoreanFood(id: 3, name: '과메기', englishName: 'Half-dried Saury'),
    KoreanFood(id: 4, name: '갈비구이', englishName: 'Grilled ribs'),
    KoreanFood(id: 5, name: '곱창구이', englishName: 'Grilled Beef Tripe'),
    KoreanFood(id: 6, name: '닭갈비', englishName: 'Spicy Stir-fried Chicken'),
    KoreanFood(id: 7, name: '더덕구이', englishName: 'Grilled Deodeok'),
    KoreanFood(id: 8, name: '떡갈비', englishName: 'Grilled Short Rib Patties'),
    KoreanFood(id: 9, name: '불고기', englishName: 'Bulgogi'),
    KoreanFood(id: 10, name: '삼겹살', englishName: 'Grilled Pork Belly'),
    KoreanFood(id: 11, name: '장어구이', englishName: 'Grilled Eel'),
    KoreanFood(id: 12, name: '조개구이', englishName: 'Grilled Clams'),
    KoreanFood(id: 13, name: '훈제오리', englishName: 'Smoked Duck'),
    KoreanFood(id: 14, name: '떡만둣국', englishName: 'Sliced Rice Cake and Dumpling Soup'),
    KoreanFood(id: 15, name: '육개장', englishName: 'Spicy Beef Soup'),
    KoreanFood(id: 16, name: '콩나물국', englishName: 'Bean Sprout Soup'),
    KoreanFood(id: 17, name: '만두', englishName: 'Dumplings'),
    KoreanFood(id: 18, name: '막국수', englishName: 'Buckwheat Noodles'),
    KoreanFood(id: 19, name: '냉면', englishName: 'Cold Noodles'),
    KoreanFood(id: 20, name: '수제비', englishName: 'Hand-pulled Dough Soup'),
    KoreanFood(id: 21, name: '국수', englishName: 'Noodles'),
    KoreanFood(id: 22, name: '짜장면', englishName: 'Jajangmyeon'),
    KoreanFood(id: 23, name: '짬뽕', englishName: 'Jjambbong'),
    KoreanFood(id: 24, name: '쫄면', englishName: 'Spicy Chewy Noodles'),
    KoreanFood(id: 25, name: '칼국수', englishName: 'Noodle Soup'),
    KoreanFood(id: 26, name: '콩국수', englishName: 'Noodles in Cold Soybean Soup'),
    KoreanFood(id: 27, name: '도토리묵', englishName: 'Acorn Jelly Salad'),
    KoreanFood(id: 28, name: '김밥', englishName: 'Gimbap'),
    KoreanFood(id: 29, name: '볶음밥', englishName: 'Fried Rice'),
    KoreanFood(id: 30, name: '비빔밥', englishName: 'Bibimbap'),
    KoreanFood(id: 31, name: '알밥', englishName: 'Fish Roe Rice'),
    KoreanFood(id: 32, name: '주먹밥', englishName: 'Riceballs'),
    KoreanFood(id: 33, name: '두부김치', englishName: 'Bean Curd with Stir-fried Kimchi'),
    KoreanFood(id: 34, name: '떡볶이', englishName: 'Stir-fried Rice Cake'),
    KoreanFood(id: 35, name: '제육볶음', englishName: 'Stir-fried Pork'),
    KoreanFood(id: 36, name: '쭈꾸미', englishName: 'Stir-fried Webfoot Octopus'),
    KoreanFood(id: 37, name: '보쌈', englishName: 'Napa Wraps with Pork'),
    KoreanFood(id: 38, name: '간장게장', englishName: 'Soy Sauce Marinated Crab'),
    KoreanFood(id: 39, name: '전', englishName: 'Pancake'),
    KoreanFood(id: 40, name: '곱창전골', englishName: 'Beef Tripe Hot Pot'),
    KoreanFood(id: 41, name: '생선조림', englishName: 'Braised Fish'),
    KoreanFood(id: 42, name: '두부조림', englishName: 'Braised Bean Curd'),
    KoreanFood(id: 43, name: '코다리조림', englishName: 'Braised Half-dried Pollack'),
    KoreanFood(id: 44, name: '죽', englishName: 'Porridge'),
    KoreanFood(id: 45, name: '김치찌개', englishName: 'Kimchi Stew'),
    KoreanFood(id: 46, name: '닭계장', englishName: 'Spicy Chicken Soup'),
    KoreanFood(id: 47, name: '동태찌개', englishName: 'Pollack Stew'),
    KoreanFood(id: 48, name: '된장찌개', englishName: 'Soybean Paste Stew'),
    KoreanFood(id: 49, name: '순두부찌개', englishName: 'Soft Bean Curd Stew'),
    KoreanFood(id: 50, name: '갈비찜', englishName: 'Braised Short Ribs'),
    KoreanFood(id: 51, name: '김치찜', englishName: 'Braised Pork with Aged Kimchi'),
    KoreanFood(id: 52, name: '꼬막찜', englishName: 'Steamed Cockles'),
    KoreanFood(id: 53, name: '닭볶음탕', englishName: 'Spicy Braised Chicken'),
    KoreanFood(id: 54, name: '수육 족발', englishName: 'Boiled Beef Slices & Braised Pigs\' Feet'),
    KoreanFood(id: 55, name: '순대', englishName: 'Sundae'),
    KoreanFood(id: 56, name: '찜닭', englishName: 'Braised Chicken'),
    KoreanFood(id: 57, name: '해물찜', englishName: 'Spicy Braised Seafood'),
    KoreanFood(id: 58, name: '갈비탕', englishName: 'Short Rib Soup'),
    KoreanFood(id: 59, name: '감자탕', englishName: 'Pork Back-bone Stew'),
    KoreanFood(id: 60, name: '설렁탕', englishName: 'Beef Bone Soup'),
    KoreanFood(id: 61, name: '매운탕', englishName: 'Spicy Fish Stew'),
    KoreanFood(id: 62, name: '삼계탕', englishName: 'Ginseng Chicken Soup'),
    KoreanFood(id: 63, name: '추어탕', englishName: 'Loach Soup'),
    KoreanFood(id: 64, name: '튀김', englishName: 'Fried Food'),
    KoreanFood(id: 65, name: '산낙지', englishName: 'Live Octopus'),
    KoreanFood(id: 66, name: '물회', englishName: 'Cold Raw Fish Soup'),
    KoreanFood(id: 67, name: '육회', englishName: 'Beef Tartare'),
  ];
}
